# Original by Spatie licensed as MIT
# https://github.com/spatie/package-skeleton-laravel/blob/main/.github/workflows/fix-php-code-style-issues.yml

name: Run Formatter

on:
  push:
    paths:
      - '.github/workflows/formatting.yml'
      - '**.php'

permissions:
  contents: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.4

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":art: Fix styling"
